apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
  namespace: namespace-workflow-1684341863769
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: acrworkflow1684283273643.azurecr.io/image-workflow-1684341863769:latest
          ports:
            - containerPort: 8080