apiVersion: v1
kind: Service
metadata:
  name: test2
  namespace: namespace-workflow-1684342103791
spec:
  type: LoadBalancer
  selector:
    app: test2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080